[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true

[tools]
1password = "latest"
act = "latest"
age = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
cloudflared = "latest"
direnv = "latest"
eza = "latest"
fnox = "latest"
fzf = "latest"
github-cli = "latest"
hyperfine = "latest"
java = "openjdk-25"
jq = "latest"
just = "latest"
lazygit = "latest"
node = "25"
opam = "latest"
pre-commit = "latest"
python = "latest"
ruff = "latest"
rust = "latest"
tlrc = "latest"
uv = "latest"
watchexec = "latest"
xxh = "latest"
zizmor = "latest"
zoxide = "latest"
